### PR TITLE
updated PHP prism references to version 1.23.0

### PR DESCRIPTION
**Pull request by mvanholsteijn**
## I generated the supported languages and parents, but I am not quite sure how you format your PHP code

The script is included (sh/generate-prism-code) and may help with future updated. Given this, I would say that it would even be possible  to make the  PHP read the required information directly from `assets/vendor/prism/components.json`.
  
## Please check the inclusion of the prism distribution:

In my local configuration (https://binx.io/blog) the php changes work fine with both the local distribution and when I point to cdnjs.cloudflare.com to obtain PrismJS 1.23.0;  

I updated the distribution included in the plugin as follows:
```bash
curl https://registry.npmjs.org/prismjs/-/prismjs-1.23.0.tgz | \
      tar --strip-components 1 -C assets/vendor/prism -xzf -
terser -o assets/vendor/prism/prism.min.js assets/vendor/prism/prism.js
```

I would appreciate a review of the asset installation. Our website works with the prismjs served from the plugin's assets.

### CODE REVIEW

**Comment by mvanholsteijn** [comment]
new languages supported in 1.23 compared to 1.15:

```
abnf			=> ABNF
agda			=> Agda
al			=> AL
antlr4			=> ANTLR4
apex			=> Apex
aql			=> AQL
bbcode			=> BBcode
birb			=> Birb
bnf			=> BNF
brightscript		=> BrightScript
bsl			=> BSL (1C:Enterprise)
cil			=> CIL
cmake			=> CMake
concurnas		=> Concurnas
cypher			=> Cypher
dataweave		=> DataWeave
dax			=> DAX
dhall			=> Dhall
dns-zone-file		=> DNS zone file
ebnf			=> EBNF
editorconfig		=> EditorConfig
ejs			=> EJS
etlua			=> Embedded Lua templating
excel-formula		=> Excel Formula
factor			=> Factor
firestore-security-rules=> Firestore security rules
ftl			=> FreeMarker Template Language
gcode			=> G-code
gdscript		=> GDScript
gml			=> GameMaker Language
hcl			=> HCL
hlsl			=> HLSL
iecst			=> Structured Text (IEC 61131-3)
ignore			=> .ignore
javadoc			=> JavaDoc
javadoclike		=> JavaDoc-like
javastacktrace		=> Java stack trace
jq			=> JQ
js-extras		=> JS Extras
js-templates		=> JS Templates
jsdoc			=> JSDoc
json5			=> JSON5
jsonp			=> JSONP
jsstacktrace		=> JS stack trace
latte			=> Latte
lilypond		=> LilyPond
llvm			=> LLVM IR
mongodb			=> MongoDB
moonscript		=> MoonScript
n1ql			=> N1QL
nand2tetris-hdl		=> Nand To Tetris HDL
naniscript		=> Naninovel Script
neon			=> NEON
pascaligo		=> Pascaligo
pcaxis			=> PC-Axis
peoplecode		=> PeopleCode
phpdoc			=> PHPDoc
powerquery		=> PowerQuery
promql			=> PromQL
purebasic		=> PureBasic
purescript		=> PureScript
qml			=> QML
racket			=> Racket
regex			=> Regex
robotframework		=> Robot Framework
shell-session		=> Shell session
smali			=> Smali
sml			=> SML
solidity		=> Solidity (Ethereum)
solution-file		=> Solution file
sparql			=> SPARQL
splunk-spl		=> Splunk SPL
sqf			=> SQF: Status Quo Function (Arma 3)
stan			=> Stan
t4-cs			=> T4 Text Templates (C#)
t4-templating		=> T4 templating
t4-vb			=> T4 Text Templates (VB)
toml			=> TOML
turtle			=> Turtle
typoscript		=> TypoScript
unrealscript		=> UnrealScript
vala			=> Vala
warpscript		=> WarpScript
xml-doc			=> XML doc (.net)
yang			=> YANG
zig			=> Zig
```

**Comment by mvanholsteijn** [comment]
@terrylinooo can you please take a look at this PR?

**Comment by CharbelHanna** [comment]
Hello, powershell and bicep are still missing in the list  can we have them added ?

**Comment by mvanholsteijn** [comment]
Hi @CharbelHanna, you would need to create a new PR

**Comment by CharbelHanna** [comment]
ah you mean i should contribute with the code ? since for the time being I am not a contributor on this project

**Comment by mvanholsteijn** [comment]
@CharbelHanna I created a PR for this. Can you test it for me?

https://github.com/mvanholsteijn/githuber-md/tree/improvement-update-to-primjs-1.25.0

**Pull request merged**
